name: Laravel Pint

on: [push, pull_request]

jobs:
  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run Laravel Pint
        run: vendor/bin/pint --test
